@extends('layouts.admin')

@section('content')
<div class="content-card p-4">
    <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><a class="text-decoration-none small" href="{{ route('admin.inquiries') }}">← Back to inquiries</a><h1 class="fw-bold mt-2 mb-1">{{ $inquiry->subject }}</h1><p class="text-muted mb-0">{{ $inquiry->category }} · received {{ $inquiry->created_at->format('M j, Y g:i A') }}</p></div><form method="POST" action="{{ route('admin.inquiries.destroy', $inquiry) }}" onsubmit="return confirm('Delete this inquiry? This cannot be undone.');">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Delete</button></form></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    <div class="row g-4"><div class="col-lg-5"><div class="card p-3 h-100"><h5>Client details</h5><p class="mb-1"><strong>{{ $inquiry->full_name }}</strong></p><p class="mb-1"><a href="mailto:{{ $inquiry->email }}">{{ $inquiry->email }}</a></p><p class="mb-0"><a href="tel:{{ $inquiry->contact_number }}">{{ $inquiry->contact_number }}</a></p><hr><p class="mb-0"><strong>Message</strong><br><span class="text-muted" style="white-space:pre-line">{{ $inquiry->message }}</span></p></div></div><div class="col-lg-7"><div class="card p-3"><h5>Reply by email</h5><p class="text-muted small">Sending records the reply and changes this inquiry to Responded.</p><form method="POST" action="{{ route('admin.inquiries.reply', $inquiry) }}">@csrf<textarea class="form-control @error('reply') is-invalid @enderror" name="reply" rows="8" required>{{ old('reply', $inquiry->admin_reply) }}</textarea>@error('reply')<div class="invalid-feedback">{{ $message }}</div>@enderror<button class="btn luxury-btn mt-3" type="submit">Send reply</button></form></div>@if($inquiry->admin_reply)<div class="card p-3 mt-4"><h5>Last sent reply</h5><p class="text-muted mb-0" style="white-space:pre-line">{{ $inquiry->admin_reply }}</p><small class="text-muted mt-2">{{ $inquiry->replied_at?->format('M j, Y g:i A') }}</small></div>@endif</div></div>
</div>
@endsection
