@extends('layouts.admin')

@section('content')
<div class="content-card p-4">
    <div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="fw-bold mb-1">Reservations</h1><p class="text-muted mb-0">Review customer information, then accept, cancel, or update each booking.</p></div><a class="btn luxury-btn align-self-md-start" href="{{ route('admin.reservations') }}">Refresh bookings</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><div class="reservation-stat reservation-stat--customers"><span>Customers</span><strong>{{ $customerCount }}</strong><small>Unique customer emails</small></div></div><div class="col-sm-6 col-xl-3"><div class="reservation-stat reservation-stat--pending"><span>Pending</span><strong>{{ $pendingCount }}</strong><small>Need a decision</small></div></div><div class="col-sm-6 col-xl-3"><div class="reservation-stat reservation-stat--accepted"><span>Accepted</span><strong>{{ $acceptedCount }}</strong><small>Confirmed bookings</small></div></div><div class="col-sm-6 col-xl-3"><div class="reservation-stat reservation-stat--cancelled"><span>Cancelled</span><strong>{{ $cancelledCount }}</strong><small>Closed bookings</small></div></div></div>

    <div class="table-responsive d-none d-md-block"><table class="table table-hover align-middle mb-0"><thead><tr><th>Customer</th><th>Event</th><th>Schedule</th><th>Guests</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($reservations as $reservation)@php($statusLabel = $reservation->status === 'confirmed' ? 'Accepted' : ucfirst($reservation->status))<tr><td><strong>{{ $reservation->full_name }}</strong><br><a class="customer-contact" href="mailto:{{ $reservation->email }}">{{ $reservation->email }}</a><br><a class="customer-contact" href="tel:{{ $reservation->contact_number }}">{{ $reservation->contact_number }}</a></td><td>{{ $reservation->event_type }}<br><small class="text-muted">{{ $reservation->venue }}</small></td><td>{{ \Carbon\Carbon::parse($reservation->event_date)->format('M j, Y') }}<br><small class="text-muted">{{ $reservation->event_time }}</small></td><td><strong>{{ $reservation->guest_count }}</strong><br><small class="text-muted">guests</small></td><td><span class="status-badge status-badge--{{ $reservation->status }}">{{ $statusLabel }}</span></td><td>@include('admin.partials.reservation-actions', ['reservation' => $reservation])</td></tr>@empty<tr><td colspan="6" class="text-center py-4 text-muted">No reservations found.</td></tr>@endforelse</tbody></table></div>

    <div class="reservation-mobile-list d-md-none">@forelse($reservations as $reservation)@php($statusLabel = $reservation->status === 'confirmed' ? 'Accepted' : ucfirst($reservation->status))<article class="reservation-mobile-card"><div class="d-flex justify-content-between gap-3"><div><h5 class="mb-1">{{ $reservation->full_name }}</h5><a class="customer-contact" href="tel:{{ $reservation->contact_number }}">{{ $reservation->contact_number }}</a></div><span class="status-badge status-badge--{{ $reservation->status }}">{{ $statusLabel }}</span></div><div class="mobile-event-info"><div><span>Event</span><strong>{{ $reservation->event_type }}</strong></div><div><span>Date</span><strong>{{ \Carbon\Carbon::parse($reservation->event_date)->format('M j, Y') }}</strong></div><div><span>Guests</span><strong>{{ $reservation->guest_count }}</strong></div></div><a class="customer-contact d-inline-block mb-3" href="mailto:{{ $reservation->email }}">{{ $reservation->email }}</a>@include('admin.partials.reservation-actions', ['reservation' => $reservation, 'mobile' => true])<details class="mt-3"><summary>View booking details</summary><div class="mobile-detail-list"><p><span>Package</span>{{ $reservation->package?->name ?? 'Custom package' }}</p><p><span>Budget</span>₱{{ number_format($reservation->estimated_budget, 2) }}</p><p><span>Venue</span>{{ $reservation->venue }}</p><p><span>Special requests</span>{{ $reservation->special_requests ?: 'None provided' }}</p></div></details></article>@empty<p class="text-center text-muted py-4">No reservations found.</p>@endforelse</div>
</div>
<style>.reservation-stat{height:100%;padding:1.1rem 1.25rem;border:1px solid var(--border);border-radius:16px;background:var(--surface-2)}.reservation-stat span,.reservation-stat small{display:block}.reservation-stat span,.mobile-event-info span,.mobile-detail-list span{font-size:.72rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.reservation-stat strong{display:block;font-size:2rem;line-height:1.15;margin:.25rem 0}.reservation-stat small,.mobile-event-info span,.mobile-detail-list span{color:var(--muted)}.reservation-stat--customers{border-left:5px solid #5279a8}.reservation-stat--pending{border-left:5px solid #d49b28}.reservation-stat--accepted{border-left:5px solid #21895b}.reservation-stat--cancelled{border-left:5px solid #c74e4e}.status-badge{display:inline-block;height:max-content;padding:.35rem .65rem;border-radius:999px;font-size:.75rem;font-weight:800}.status-badge--pending{color:#714d00;background:#fff1c9}.status-badge--confirmed{color:#0a5a35;background:#d9f7e6}.status-badge--completed{color:#164f85;background:#dceeff}.status-badge--cancelled{color:#8d2020;background:#ffe0e0}.customer-contact{font-size:.82rem;color:var(--accent);text-decoration:none}.reservation-mobile-card{padding:1.1rem;margin-bottom:1rem;border:1px solid var(--border);border-radius:16px;background:var(--surface)}.reservation-mobile-card h5{font-size:1rem}.mobile-event-info{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;padding:1rem 0}.mobile-event-info strong{display:block;font-size:.82rem;margin-top:.15rem}.mobile-detail-list{padding-top:.75rem}.mobile-detail-list p{margin:0 0 .65rem}.mobile-detail-list p:last-child{margin:0}.reservation-mobile-card summary{cursor:pointer;font-weight:700;color:var(--accent)}.reservation-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.5rem}.reservation-actions form{display:flex;gap:.5rem}.reservation-actions .form-select{width:auto}@media(max-width:767px){.reservation-actions{justify-content:stretch;margin-top:.25rem}.reservation-actions form{flex:1}.reservation-actions .quick-action{width:100%}.reservation-actions .form-select{width:100%}}body.dark-mode .reservation-stat,body.dark-mode .reservation-mobile-card{background:#293548;border-color:#475569}body.dark-mode .customer-contact{color:#f5c69f}body.dark-mode .status-badge--pending{color:#ffe6a3;background:#5d430b}body.dark-mode .status-badge--confirmed{color:#baf3d1;background:#0a5232}body.dark-mode .status-badge--completed{color:#b8dcff;background:#123f68}body.dark-mode .status-badge--cancelled{color:#ffc3c3;background:#6f1f25}</style>
@endsection
